version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    environment:
      - PROTOC_VERSION: "3.5.1"
    working_directory: /go/src/github.com/telecom-tower/towerapi
    steps:
      - checkout
      - run:
          command: wget -q -nc https://github.com/google/protobuf/releases/download/v${PROTOC_VERSION}/protoc-${PROTOC_VERSION}-linux-x86_64.zip
          working_directory: /tmp
      - run:
          command: sudo unzip /tmp/protoc-${PROTOC_VERSION}-linux-x86_64.zip
          working_directory: /usr/local
      - run: sudo chmod +x /usr/local/bin/protoc
      - run: go get -u google.golang.org/grpc
      - run: go get -u github.com/golang/protobuf/protoc-gen-go
      - run: protoc -I v1 v1/telecomtower.proto --go_out=plugins=grpc:v1