version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
      
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - run:
          command: wget -q -nc https://github.com/google/protobuf/releases/download/v3.5.1/protoc-3.5.1-linux-x86_64.zip
          working_directory: /tmp
      - run:
          command: unzip /tmp/protoc-3.5.1-linux-x86_64.zip
          working_directory: /usr/local
      - run: go get -u google.golang.org/grpc
      - run: go get -u github.com/golang/protobuf/protoc-gen-go
      - run: protoc -I v1 v1/telecomtower.proto --go_out=plugins=grpc:v1